version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footprint
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci",'--default-time-zone=+09:00' ]
  web:
    image: huipulco/footprint:latest
    container_name: footprint-api
    restart: on-failure
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - db