version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footprint
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci",'--default-time-zone=+09:00' ]
  web:
    build: .
    container_name: footprint-api
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://db:3306/footprint
      DB_USER: user
      DB_PASSWORD: mypass
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      JWT_SECRET: ZG9uZ2h1bi1zaGFycC1kYnJ1YS13ZWItcHJvamVjdC11c2luZy1qd3Qtc2VjcmV0LURvbmdodW4tc3ByaW5nLWJvb3Qtand0LWJhY2stZW5kLWFuZC1qcy1jb2xsYWJv
      JWT_EXPIRATION: 3
    depends_on:
      - db